// AUTO-GENERATED by code/goolets/snapshot-mtd-thumbs.js — do not edit by hand.
// Current month + frozen monthly archives, newest-first after 'current'.
import current from './mtd-data.json';
import m202607 from './archive/2026-07.json';

export const MONTHS = [
  { key: 'current', label: 'This month', data: current },
  { key: '2026-07', label: 'Julij 2026', data: m202607 }
];
