// AUTO-GENERATED by code/goolets/snapshot-mtd-thumbs.js — do not edit by hand.
// Current month + frozen monthly archives, newest-first after 'current'.
import current from './mtd-data.json';

export const MONTHS = [
  { key: 'current', label: 'This month', data: current }
];
